global:
  scrape_interval: 1s

scrape_configs:
  - job_name: 'readApi'
    scrape_interval: 1s
    static_configs:
      - targets: ['host.docker.internal:5050']
  - job_name: 'contactsApi'
    scrape_interval: 1s
    static_configs:
      - targets: ['host.docker.internal:5221']