apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-api
spec:
  selector:
    matchLabels:
      app: auth-api
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-api
          image: sergiofdf/auth-api:latest
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 8080
          - name: https
            containerPort: 8081
          env:
          - name: ConnectionStrings__techchallenge01
            valueFrom:
              secretKeyRef:
                name: database-secret-config
                key: connectionstring
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: auth-api
spec:
  type: ClusterIP
  selector:
    app: auth-api
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  - name: https
    port: 8081
    targetPort: 8081
