apiVersion: apps/v1
kind: Deployment
metadata:
  name: read-api
spec:
  selector:
    matchLabels:
      app: read-api
  replicas: 1
  template:
    metadata:
      labels:
        app: read-api
    spec:
      containers:
        - name: read-api
          image: sergiofdf/contact-read-api:latest
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 8084
          - name: https
            containerPort: 8085
          env:
          - name: ConnectionStrings__techchallenge01
            valueFrom:
              secretKeyRef:
                name: database-secret-config
                key: connectionstring
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: read-api
spec:
  type: ClusterIP
  selector:
    app: read-api
  ports:
  - name: http
    port: 8084
    targetPort: 8084
  - name: https
    port: 8085
    targetPort: 8085
