apiVersion: v1
kind: Secret
metadata:
  name: database-secret-config
type: Opaque
stringData:
  dbname: postgresdb
  username: postech
  password: postech
  connectionstring: "Host=postgres;Port=5432;Database=techchallenge01;Username=postech;Password=postech;Include Error Detail=true"